// Builds the deployable v2 site into ../../site-v2/ from page-template.js (copy + markup),
// ../ds-bundle/styles.css (design system) and ../../assets/prepared/web/ (images).
// Run: node build-site.js      Output is generated: never edit site-v2/ by hand, edit the sources and rebuild.
const fs = require('fs'), path = require('path');
const T = require('./page-template.js');
// English ships only once copy-en.js and meta-en.js exist. Until then the EN entry is dropped from the
// switcher, so the header never links to a page that is not built.
const EN_COPY = path.join(__dirname, 'copy-en.js'), EN_META = path.join(__dirname, 'meta-en.js');
const HAS_EN = fs.existsSync(EN_COPY) && fs.existsSync(EN_META);
if (!HAS_EN) { const i = T.LANGS.findIndex(l => l[0] === 'en'); if (i > -1) T.LANGS.splice(i, 1); }
const COPY = { fr: T.FR, nl: T.NL };
if (HAS_EN) COPY.en = require(EN_COPY);
const LEGAL_TEXT = require('./legal.js'); // the privacy page text, one <main> per language
const ROOT = path.resolve(__dirname, '..', '..');
// The hero-ticker design IS the site since 2026-08-25 (Fady's merge call, DECISIONS.md): no flag, one
// build, one output. The classic hero stays parked in page-template.js behind opts.ticker=false and the
// chips behind one CSS rule in ds-bundle/styles.css; nothing parked is deleted (README, "Parked options").
const HERO_TICKER = true;
// ADS_TAG_ID=AW-XXXXXXXXXX (set at the Ads session, ads-program.md) builds the consent + Google-tag
// layer: Consent Mode v2 default-denied stub first in <head>, the banner (assets/js/consent.js, equal
// Refuse/Accept, localStorage only, 182 days), the tag-day footer credit and privacy section, the reopen
// link, and the Google CSP. WITHOUT the flag the output is byte-identical to the tag-free site: no
// banner markup, no stub, no dormant JS (research/13 section 8.3), and every "no cookies" line stays true.
// ADS_CALL_LABEL / ADS_WA_LABEL (optional, same session) add the two conversion send_to labels.
const ADS_TAG_ID = process.env.ADS_TAG_ID || '';
const ADS_CALL_LABEL = process.env.ADS_CALL_LABEL || '';
const ADS_WA_LABEL = process.env.ADS_WA_LABEL || '';
const CONSENT_VER = '2026-08-25'; // bump when the banner or privacy text changes: the banner re-asks
const OUT = path.join(ROOT, 'site-v2');
const WEB = path.join(ROOT, 'assets', 'prepared', 'web');
const DS = path.join(ROOT, 'design', 'ds-bundle');
const BUILD_YEAR = '2026';
const HOST = 'https://prodebouchage24.be';

const rm = p => fs.rmSync(p, { recursive: true, force: true });
const mk = p => fs.mkdirSync(p, { recursive: true });
const cp = (a, b) => { mk(path.dirname(b)); fs.copyFileSync(a, b); };
const w = (rel, s) => { const p = path.join(OUT, rel); mk(path.dirname(p)); fs.writeFileSync(p, s, 'utf8'); };

mk(OUT); for (const e of fs.readdirSync(OUT)) rm(path.join(OUT, e));

// ---------- assets ----------
// fonts
for (const f of ['archivo-latin.woff2', 'archivo-latin-ext.woff2']) cp(path.join(DS, 'fonts', f), path.join(OUT, 'assets', 'fonts', f));
// css: inline the @font-face with absolute font paths, drop the @import, append the page extras
let css = fs.readFileSync(path.join(DS, 'styles.css'), 'utf8').replace(/@import[^\n]*\n/, '');
let fontsCss = fs.readFileSync(path.join(DS, 'fonts', 'fonts.css'), 'utf8').replace(/url\("archivo-/g, 'url("/assets/fonts/archivo-');
const { extraCss } = T.pageHtml(T.FR, { mode: 'site' });
css = '/* Generated by design/canvas-v2/build-site.js from design/ds-bundle/styles.css. Do not edit here. */\n' + fontsCss + '\n' + css + '\n/* page extras */\n' + extraCss + '\n';
if (ADS_TAG_ID) css += `
/* consent card + reopen link (built only with ADS_TAG_ID) */
.linklike{background:none;border:0;padding:0;font:inherit;color:inherit;text-decoration:underline;cursor:pointer}
.consent{position:fixed;left:16px;right:16px;bottom:calc(72px + env(safe-area-inset-bottom));z-index:190;background:#fff;color:var(--ink);border:1px solid rgba(16,42,74,.15);border-radius:12px;box-shadow:0 8px 30px rgba(16,42,74,.18);padding:16px;max-width:420px;margin-inline:auto}
@media (min-width:1000px){.consent{left:auto;right:24px;bottom:24px;margin:0}}
.consent h2{font-size:1.0625rem;margin:0 0 8px}
.consent p{font-size:.9375rem;margin:0 0 12px}
.consent .c-btns{display:flex;gap:8px}
.consent .c-btns button{flex:1;font:inherit;font-weight:800;font-size:.9375rem;padding:10px 12px;border-radius:10px;cursor:pointer;border:2px solid var(--ink);background:#fff;color:var(--ink)}
`;
w('assets/css/style.css', css);
// content-hashed query so a redeploy always busts the 24h browser cache on style.css
const CSSV = require('crypto').createHash('md5').update(css).digest('hex').slice(0, 8);

// consent.js: written only with ADS_TAG_ID (research/13 sections 8.1 and 8.3). Nothing from Google is
// requested before an explicit accept; refuse after accept wipes the _ga*/_gcl* cookies; the choice
// lives in localStorage (no cookie), 182 days, re-asked when CONSENT_VER bumps.
if (ADS_TAG_ID) {
  const STR = {};
  for (const [l] of T.LANGS) STR[l] = { t: COPY[l].consentT, p: COPY[l].consentP, refuse: COPY[l].consentRefuse, accept: COPY[l].consentAccept };
  w('assets/js/consent.js', `// Generated by design/canvas-v2/build-site.js. Do not edit here.
(function(){
var ID=${JSON.stringify(ADS_TAG_ID)},CALL=${JSON.stringify(ADS_CALL_LABEL)},WA=${JSON.stringify(ADS_WA_LABEL)};
var KEY='pd_consent',VER=${JSON.stringify(CONSENT_VER)},DAYS=182;
var STR=${JSON.stringify(STR)};
var s=STR[(document.documentElement.lang||'fr').slice(0,2)]||STR.fr;
function read(){try{var r=JSON.parse(localStorage.getItem(KEY));if(!r||r.v!==VER)return null;if(Date.now()-r.t>DAYS*864e5){localStorage.removeItem(KEY);return null}return r}catch(e){return null}}
function save(ok){try{localStorage.setItem(KEY,JSON.stringify({ads:ok,v:VER,t:Date.now()}))}catch(e){}}
var loaded=false;
function enable(){if(loaded)return;loaded=true;
gtag('consent','update',{ad_storage:'granted',ad_user_data:'granted',analytics_storage:'granted'});
var sc=document.createElement('script');sc.async=true;sc.src='https://www.googletagmanager.com/gtag/js?id='+ID;document.head.appendChild(sc);
gtag('js',new Date());gtag('config',ID);}
function wipe(){document.cookie.split(';').forEach(function(c){var n=c.split('=')[0].trim();if(!/^(_ga|_gcl)/.test(n))return;
['','domain='+location.hostname+';','domain=.'+location.hostname+';'].forEach(function(d){document.cookie=n+'=;path=/;'+d+'expires=Thu, 01 Jan 1970 00:00:00 GMT';});});}
var card=null;
function close(){if(card){card.remove();card=null}}
function show(){if(card)return;
card=document.createElement('div');card.className='consent';card.setAttribute('role','dialog');card.setAttribute('aria-label',s.t);
card.innerHTML='<h2>'+s.t+'</h2><p>'+s.p+'</p><div class="c-btns"><button type="button" data-c="0">'+s.refuse+'</button><button type="button" data-c="1">'+s.accept+'</button></div>';
card.addEventListener('click',function(e){var b=e.target.closest('button[data-c]');if(!b)return;var ok=b.dataset.c==='1';save(ok);close();if(ok)enable();else wipe();});
document.body.appendChild(card);}
document.addEventListener('click',function(e){
if(e.target.closest('[data-consent-open]')){show();return}
var a=e.target.closest('a[data-cta]');if(!a||!loaded)return;
var isWa=a.dataset.cta.indexOf('whatsapp')>-1;
gtag('event',isWa?'whatsapp_click':'call_click',{cta:a.dataset.cta});
var lb=isWa?WA:CALL;if(lb)gtag('event','conversion',{send_to:ID+'/'+lb});
});
var r=read();if(!r)show();else if(r.ads)enable();
})();
`);
}

// images: the manifest names -> exported sizes
const IMGS = {
  'collage-van.webp':   { base: 'hero-van-wide', widths: [800, 1200, 1600], w: 1600, h: 900, sizes: '(min-width: 1000px) 400px, 100vw' },
  'collage-job1.webp':  { base: 'hero-job-1', widths: [480, 800], w: 800, h: 1000, sizes: '(min-width: 1000px) 194px, 100vw' },
  'collage-job2.webp':  { base: 'hero-job-2', widths: [480, 770], w: 770, h: 962, sizes: '(min-width: 1000px) 194px, 100vw' },
  'van-studio.webp': { base: 'van-studio', widths: [800, 1200, 1600], w: 1600, h: 893, sizes: '(min-width: 1000px) 640px, 100vw' },
  'job-wc.webp':     { base: 'job-wc', widths: [480, 800, 1200], w: 1200, h: 1500, sizes: '(min-width: 1000px) 360px, (min-width: 700px) 50vw, 100vw' },
  'machine.webp':    { base: 'machine-haute-pression', widths: [480, 800, 1200], w: 1200, h: 1500, sizes: '(min-width: 1000px) 360px, (min-width: 700px) 50vw, 100vw' },
  'camera.webp':     { base: 'camera-ecran', widths: [480, 800, 1200], w: 1200, h: 1500, sizes: '(min-width: 1000px) 360px, (min-width: 700px) 50vw, 100vw' },
  'chambre.webp':    { base: 'chambre-visite-jardin', widths: [480, 800], w: 800, h: 1000, sizes: '(min-width: 1000px) 360px, 50vw' },
  'siphon.webp':     { base: 'camera-siphon', widths: [480, 800], w: 800, h: 1000, sizes: '(min-width: 1000px) 360px, 50vw' },
  'allee.webp':      { base: 'allee-haute-pression', widths: [480, 800, 1200], w: 1200, h: 1200, sizes: '(min-width: 1000px) 360px, 50vw' },
  'moniteur.webp':   { base: 'camera-moniteur-tenue', widths: [480, 800], w: 800, h: 1000, sizes: '(min-width: 1000px) 360px, 100vw' },
  // Ticker-only images (hero variant): rendered at a fixed strip height, width follows the aspect.
  'tick-drain.webp': { base: 'hero-job-drain', widths: [480, 800], w: 800, h: 1066, sizes: '(min-width: 820px) 240px, 115px' },
  'tick-van.webp':   { base: 'van-photo', widths: [800, 1200], w: 1200, h: 892, sizes: '(min-width: 820px) 430px, 205px' },
  // Mobile-carousel lead image: the enhanced garden van, 4:5 (from assets/raw/pro-debouchage-car-2-enhanced.jpeg,
  // Fady's 2026-08-24 night update; variants generated with sharp). Carousel-only, so mobile-width sizes.
  'car-van.webp':    { base: 'van-garden-45', widths: [480, 800], w: 800, h: 1000, sizes: '92vw' },
};
for (const k in IMGS) {
  const m = IMGS[k];
  for (const wd of m.widths) for (const ext of ['avif', 'webp']) cp(path.join(WEB, 'img', `${m.base}-${wd}.${ext}`), path.join(OUT, 'assets', 'img', `${m.base}-${wd}.${ext}`));
  const last = m.widths[m.widths.length - 1];
  cp(path.join(WEB, 'img', `${m.base}-${last}.jpg`), path.join(OUT, 'assets', 'img', `${m.base}-${last}.jpg`));
}
for (const f of ['logo-icon.svg', 'og-banner.jpg', 'icon-512.png', 'icon-512-maskable.png']) cp(path.join(WEB, 'img', f), path.join(OUT, 'assets', 'img', f));
cp(path.join(WEB, 'img', 'favicon.svg'), path.join(OUT, 'favicon.svg'));
cp(path.join(WEB, 'img', 'apple-touch-icon-180.png'), path.join(OUT, 'apple-touch-icon.png'));

function IMG(name, alt, w0, h0, extra) {
  // The header and footer show the monogram alone (Fady's own SVG, no wordmark). It is one small vector file, so it is
  // inlined as a normal <img> rather than a <picture>: no raster fallback is needed and it stays crisp at any size.
  if (name === 'logo-icon.svg') return `<img src="/assets/img/logo-icon.svg" width="816" height="499" alt="${alt}"${extra ? ' ' + extra : ''}>`;
  const m = IMGS[name]; if (!m) throw new Error('unknown image ' + name);
  const set = ext => m.widths.map(wd => `/assets/img/${m.base}-${wd}.${ext} ${wd}w`).join(', ');
  const last = m.widths[m.widths.length - 1];
  return `<picture><source type="image/avif" srcset="${set('avif')}" sizes="${m.sizes}"><source type="image/webp" srcset="${set('webp')}" sizes="${m.sizes}"><img src="/assets/img/${m.base}-${last}.jpg" width="${m.w}" height="${m.h}" alt="${alt}"${extra ? ' ' + extra : ''}></picture>`;
}

// ---------- head ----------
const META = {
  fr: { title: 'Débouchage 24h/24 autour de Bruxelles | Prix dit au téléphone',
        desc: 'Canalisation, WC ou égout bouché ? Déboucheur basé à Vilvorde, autour de Bruxelles, 24h/24. Prix dit au téléphone, confirmé à votre porte. 0480 649 649.',
        ogt: 'Ça remonte, ça déborde, ça pue&#8239;? Appelez, on s\'en occupe.', ogd: 'Déboucheur à Vilvorde, autour de Bruxelles, 24h/24. Le prix annoncé au téléphone est le prix sur la facture.', locale: 'fr_BE',
        ogAlt: 'Camionnette Pro Débouchage avec le numéro 0480 649 649' },
  nl: { title: 'Ontstopping 24/7 rond Brussel | Prijs aan de telefoon',
        desc: 'Verstopte afvoer, wc of riool? Ontstoppingsdienst uit Vilvoorde, rond Brussel. 24/7. Prijs aan de telefoon, bevestigd aan de deur. Camera inbegrepen. Bel 0480 649 649.',
        ogt: 'Loopt het terug, loopt het over, stinkt het? Bel, wij lossen het op.', ogd: 'Ontstoppingsdienst in Vilvoorde, rond Brussel, 24/7. De prijs die u aan de telefoon hoort, staat op de factuur.', locale: 'nl_BE',
        ogAlt: 'Bestelwagen van Pro Débouchage met het nummer 0480 649 649' },
};
if (HAS_EN) META.en = require(EN_META);
function head(lang, paths, m, opts = {}) {
  const self = paths[lang];
  const alts = Object.entries(paths).map(([l, p]) => `<link rel="alternate" hreflang="${l}-BE" href="${HOST}${p}">`).join('\n');
  const hero = IMGS['collage-van.webp'];
  const pre = opts.hero ? `<link rel="preload" as="image" type="image/avif" imagesrcset="${hero.widths.map(wd => `/assets/img/${hero.base}-${wd}.avif ${wd}w`).join(', ')}" imagesizes="${hero.sizes}" fetchpriority="high">` : '';
  return `<!DOCTYPE html>
<!-- Generated by design/canvas-v2/build-site.js. Do not edit by hand: edit design/canvas-v2/page-template.js or design/ds-bundle/styles.css and rebuild. -->
<html lang="${lang}-BE">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">${ADS_TAG_ID ? `
<script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('consent','default',{ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied',analytics_storage:'denied',wait_for_update:500});</script>` : ''}
<title>${m.title}</title>
<meta name="description" content="${m.desc}">
<link rel="canonical" href="${HOST}${self}">
${alts}
<link rel="alternate" hreflang="x-default" href="${HOST}${paths.fr}">
<meta name="robots" content="${opts.noindex ? 'noindex, follow' : 'index, follow'}">
<meta name="theme-color" content="#102A4A">
<meta property="og:type" content="website">
<meta property="og:locale" content="${m.locale}">
<meta property="og:url" content="${HOST}${self}">
<meta property="og:site_name" content="Pro Débouchage">
<meta property="og:title" content="${m.ogt}">
<meta property="og:description" content="${m.ogd}">
<meta property="og:image" content="${HOST}/assets/img/og-banner.jpg">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="${m.ogAlt}">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="manifest" href="/site.webmanifest">
${pre}
<link rel="preload" as="font" type="font/woff2" href="/assets/fonts/archivo-latin.woff2" crossorigin>
<link rel="stylesheet" href="/assets/css/style.css?v=${CSSV}">
</head>
<body>
`;
}
// Floating guarantee badge: open on click; ANY close (badge again, outside click, Escape) also fades
// the whole badge away for the rest of the visit. Seen once, it leaves the page (Fady 2026-08-25).
const GUAR_JS = `function guarBye(){var w=document.querySelector('.guar-float');if(!w)return;var pop=document.getElementById('guar-pop');pop.setAttribute('hidden','');w.querySelector('[data-guar-toggle]').setAttribute('aria-expanded','false');w.classList.add('guar-bye')}
document.addEventListener('click',function(e){var pop=document.getElementById('guar-pop');if(!pop)return;var btn=document.querySelector('[data-guar-toggle]');if(e.target.closest('[data-guar-toggle]')){if(pop.hasAttribute('hidden')){pop.removeAttribute('hidden');btn.setAttribute('aria-expanded','true')}else{guarBye()}}else if(!pop.hasAttribute('hidden')&&!e.target.closest('.guar-float')){guarBye()}});
document.addEventListener('keydown',function(e){var pop=document.getElementById('guar-pop');if(e.key==='Escape'&&pop&&!pop.hasAttribute('hidden')){guarBye()}});
(function(){var band=document.querySelector('aside.guar');var w=document.querySelector('.guar-float');if(!band||!w||!('IntersectionObserver' in window))return;new IntersectionObserver(function(es){es.forEach(function(en){var pop=document.getElementById('guar-pop');if(en.isIntersecting&&pop&&!pop.hasAttribute('hidden'))return;w.classList.toggle('guar-away',en.isIntersecting)})},{threshold:0.2}).observe(band)})();`;
const TAIL = ADS_TAG_ID ? `
<script>document.getElementById('y').textContent=new Date().getFullYear();
${GUAR_JS}</script>
<script src="/assets/js/consent.js" defer></script>
</body>
</html>
` : `
<!-- consent + tags mount here -->
<script>document.getElementById('y').textContent=new Date().getFullYear();
document.addEventListener('click',function(e){var a=e.target.closest('a[data-cta]');if(!a)return;/* later: gtag('event', a.dataset.cta.indexOf('whatsapp')>-1?'whatsapp_click':'call_click', {cta:a.dataset.cta}) */});
${GUAR_JS}</script>
</body>
</html>
`;

// ---------- JSON-LD ----------
function jsonld(c, lang) {
  const towns = c.towns.map(t => ({ '@type': 'City', name: t }));
  const faq = c.faq.map(q => ({ '@type': 'Question', name: strip(q[0]), acceptedAnswer: { '@type': 'Answer', text: strip(q[1]) } }));
  const data = { '@context': 'https://schema.org', '@graph': [
    { '@type': 'Plumber', '@id': HOST + '/#business', name: 'Pro Débouchage', legalName: 'PRO DEBOUCHAGE SRL', url: HOST + '/' + lang + '/', telephone: '+32480649649', email: 'info@prodebouchage24.be',
      image: HOST + '/assets/img/og-banner.jpg', identifier: 'BE 1027.454.187',
      address: { '@type': 'PostalAddress', streetAddress: 'Guldenschaapstraat 6', postalCode: '1800', addressLocality: 'Vilvoorde', addressCountry: 'BE' },
      openingHoursSpecification: [{ '@type': 'OpeningHoursSpecification', dayOfWeek: ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'], opens: '00:00', closes: '23:59' }],
      areaServed: towns },
    { '@type': 'FAQPage', '@id': HOST + '/' + lang + '/#faq', inLanguage: lang + '-BE', mainEntity: faq },
  ] };
  return `<script type="application/ld+json">\n${JSON.stringify(data, null, 1)}\n</script>`;
}
const strip = s => s.replace(/&#8239;/g, ' ').replace(/<[^>]+>/g, '');

// ---------- pages ----------
const LANDING = {}; for (const [l] of T.LANGS) LANDING[l] = '/' + l + '/';
// Where each language's footer privacy link points: its own language, always. Extensionless, like every
// other link on the site.
const LEGAL_PATH = { fr: '/fr/confidentialite', nl: '/nl/privacy', en: '/en/privacy' };
const LEGAL = {}; for (const [l] of T.LANGS) LEGAL[l] = LEGAL_PATH[l];
const shell = (c, lang) => T.pageHtml(c, { mode: 'site', img: IMG, privacyHref: LEGAL[lang], ticker: HERO_TICKER, adsTag: !!ADS_TAG_ID });
function landing(c, lang) {
  const { body } = shell(c, lang);
  // The collage preload only helps the classic hero; the ticker loads its first images eagerly itself.
  return head(lang, LANDING, META[lang], { hero: !HERO_TICKER }) + body + '\n' + jsonld(c, lang) + TAIL;
}
for (const [l] of T.LANGS) w(l + '/index.html', landing(COPY[l], l));

// privacy pages: the legal text (main only, from legal.js) under the v2 shell, one page per language.
function legalShell(lang, paths, title, desc) {
  // The cookies section swaps with the tag: day-one text without ADS_TAG_ID (markers stripped so the
  // output is byte-identical to the pre-flag build), the COOKIES_TAG text with it.
  const main = ADS_TAG_ID
    ? LEGAL_TEXT[lang].replace(/<!--cookies-->[\s\S]*?<!--\/cookies-->/, LEGAL_TEXT.COOKIES_TAG[lang])
    : LEGAL_TEXT[lang].replace('<!--cookies-->\n', '').replace('\n<!--/cookies-->', '');
  const c = COPY[lang];
  const { body } = shell(c, lang);
  let header = body.match(/<header[\s\S]*?<\/header>/)[0];
  for (const [l, p] of Object.entries(paths)) header = header.replace(`href="/${l}/" lang="${l}"`, `href="${p}" lang="${l}"`);
  const footer = body.match(/<footer[\s\S]*?<\/footer>/)[0];
  const bar = body.match(/<div class="callbar"[\s\S]*?<\/div>/)[0];
  const m = { title, desc, ogt: title, ogd: desc, locale: META[lang].locale, ogAlt: META[lang].ogAlt };
  // the legal <main> carries no id, so give it the one the skip link targets
  return head(lang, paths, m) + `<a class="skip" href="#contenu">${c.skip}</a>\n` + header + '\n' + main.replace('<main', '<main class="wrap doc" id="contenu" style="padding:48px 16px"') + '\n' + footer + '\n' + bar + TAIL;
}
const LEGAL_FILE = { fr: 'fr/confidentialite.html', nl: 'nl/privacy.html', en: 'en/privacy.html' };
const LEGAL_META = {
  fr: ['Politique de vie privée | Pro Débouchage', 'Politique de vie privée de PRO DEBOUCHAGE SRL. Quelles données nous traitons, pourquoi, combien de temps, et vos droits.'],
  nl: ['Privacybeleid | Pro Débouchage', 'Privacybeleid van PRO DEBOUCHAGE SRL. Welke gegevens wij verwerken, waarom, hoelang, en uw rechten.'],
  en: ['Privacy policy | Pro Débouchage', 'Privacy policy of PRO DEBOUCHAGE SRL. What data we handle, why, for how long, and your rights.'],
};
for (const [l] of T.LANGS) w(LEGAL_FILE[l], legalShell(l, LEGAL, LEGAL_META[l][0], LEGAL_META[l][1]));

// root chooser
const CHOOSE = { fr: ['Français', 'Débouchage 24h/24'], nl: ['Nederlands', 'Ontstopping 24/7'], en: ['English', 'Drain unblocking 24/7'] };
const chooserBtns = T.LANGS.map(([l]) => `<a class="btn btn-ghost" href="/${l}/" lang="${l}" hreflang="${l}-BE">${CHOOSE[l][0]} &rarr; ${CHOOSE[l][1]}</a>`).join('\n');
const chooserTitle = T.LANGS.map(([l]) => CHOOSE[l][0]).join(' &middot; ');
w('index.html', head('fr', LANDING, { title: 'Pro Débouchage, Vilvorde | ' + chooserTitle.replace(/&middot;/g, '·'), desc: 'Débouchage 24h/24 autour de Bruxelles. Choisissez votre langue. Ontstopping 24/7 rond Brussel. Kies uw taal. Drain unblocking around Brussels, 24/7. 0480 649 649.', ogt: 'Pro Débouchage', ogd: 'Débouchage 24h/24 autour de Bruxelles. Ontstopping 24/7 rond Brussel. Drain unblocking around Brussels, 24/7.', locale: 'fr_BE', ogAlt: META.fr.ogAlt }, { noindex: true }).replace('<body>', '<body style="padding:0">') + `
<main class="chooser"><div class="box">
${IMG('logo-icon.svg', 'Pro Débouchage', 320, 200, '')}
<h1 style="font-size:1.5rem">${chooserTitle}</h1>
<p class="lead" style="font-size:1rem">Choisissez votre langue. Kies uw taal. Choose your language.</p>
${chooserBtns}
<p style="margin-top:24px"><a class="btn btn-call" href="tel:+32480649649" data-cta="chooser-call">${T.PHONE}0480 649 649</a></p>
<p style="font-size:0.875rem;color:var(--muted);margin-bottom:0">PRO DEBOUCHAGE SRL, Guldenschaapstraat 6, 1800 Vilvoorde. BE 1027.454.187.</p>
</div></main>
<span id="y" hidden>${BUILD_YEAR}</span>
` + TAIL);

// 404, bilingual
const NOTFOUND = {
  fr: [`Cette page n'existe pas.`, 'Mais nous, oui.', 'Appeler 0480 649 649', `Retour à la page d'accueil`],
  nl: ['Deze pagina bestaat niet.', 'Wij wel.', 'Bel 0480 649 649', 'Terug naar de startpagina'],
  en: ['This page does not exist.', 'We do.', 'Call 0480 649 649', 'Back to the home page'],
};
const nf = T.LANGS.map(([l], i) => `${i ? '<hr class="rule" style="margin:24px auto">\n' : ''}<h${i ? 2 : 1} style="font-size:${i ? '1.4rem' : '1.6rem'}" lang="${l}">${NOTFOUND[l][0]}</h${i ? 2 : 1}>
<p class="lead" lang="${l}">${NOTFOUND[l][1]}</p>
<p><a class="btn btn-call" href="tel:+32480649649" data-cta="404-call-${l}" lang="${l}">${T.PHONE}${NOTFOUND[l][2]}</a></p>
<p><a href="/${l}/" lang="${l}">${NOTFOUND[l][3]}</a></p>`).join('\n');
w('404.html', head('fr', LANDING, { title: 'Page introuvable | Pro Débouchage', desc: 'Cette page n\'existe pas. Appelez le 0480 649 649.', ogt: 'Pro Débouchage', ogd: 'Débouchage 24h/24 autour de Bruxelles.', locale: 'fr_BE', ogAlt: META.fr.ogAlt }, { noindex: true }).replace('<body>', '<body style="padding:0">') + `
<main class="chooser"><div class="box">
${IMG('logo-icon.svg', 'Pro Débouchage', 320, 200, '')}
${nf}
</div></main>
<span id="y" hidden>${BUILD_YEAR}</span>
` + TAIL);

// static files
w('robots.txt', `# Pro Débouchage, prodebouchage24.be\nUser-agent: *\nAllow: /\n\nSitemap: ${HOST}/sitemap.xml\n`);
const today = '2026-08-24';
// One <url> per page, each carrying the full alternate set of its own group.
const url = (loc, paths) => `  <url>\n    <loc>${HOST}${loc}</loc>\n    <lastmod>${today}</lastmod>\n` +
  Object.entries(paths).map(([l, p]) => `    <xhtml:link rel="alternate" hreflang="${l}-BE" href="${HOST}${p}"/>\n`).join('') +
  `    <xhtml:link rel="alternate" hreflang="x-default" href="${HOST}${paths.fr}"/>\n  </url>\n`;
const urls = Object.values(LANDING).map(p => url(p, LANDING)).join('') + Object.values(LEGAL).map(p => url(p, LEGAL)).join('');
w('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n${urls}</urlset>\n`);
w('site.webmanifest', JSON.stringify({ name: 'Pro Débouchage', short_name: 'Pro Débouchage', start_url: '/fr/', display: 'browser', background_color: '#F6F3EE', theme_color: '#102A4A', icons: [{ src: '/assets/img/icon-512.png', sizes: '512x512', type: 'image/png' }, { src: '/assets/img/icon-512-maskable.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' }] }, null, 2));
// Two CSPs (research/13 section 2.3): the tag-free day-one line, and the Google line the moment
// ADS_TAG_ID exists. The inactive one rides along commented so the swap stays visible in the output.
const CSP_DAY1 = `Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self'; font-src 'self'; connect-src 'self'; frame-src 'none'; media-src 'self'; manifest-src 'self'; object-src 'none'; base-uri 'self'; form-action 'none'; frame-ancestors 'none'; upgrade-insecure-requests`;
const CSP_TAG = `Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' https://*.googletagmanager.com https://*.googleadservices.com https://googleads.g.doubleclick.net https://pagead2.googlesyndication.com; style-src 'self' 'unsafe-inline'; img-src 'self' https://*.googletagmanager.com https://*.google-analytics.com https://*.googleadservices.com https://*.doubleclick.net https://*.google.com https://*.google.be https://*.google.nl https://*.google.fr; font-src 'self'; connect-src 'self' https://*.googletagmanager.com https://*.google-analytics.com https://*.analytics.google.com https://*.googleadservices.com https://*.doubleclick.net https://pagead2.googlesyndication.com https://*.google.com https://*.google.be https://*.google.nl https://*.google.fr; frame-src https://td.doubleclick.net https://www.googletagmanager.com; media-src 'self'; manifest-src 'self'; object-src 'none'; base-uri 'self'; form-action 'none'; frame-ancestors 'none'; upgrade-insecure-requests`;
w('_headers', `/*
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=()
  ${ADS_TAG_ID ? CSP_TAG : CSP_DAY1}

# Preview hosts only: never index *.pages.dev. The real domain is unaffected.
https://prodebouchage24.pages.dev/*
  X-Robots-Tag: noindex
https://:version.prodebouchage24.pages.dev/*
  X-Robots-Tag: noindex

# One rule per file type. Overlapping rules append, they never override.
/assets/fonts/*
  Cache-Control: public, max-age=31536000, immutable
/assets/css/style.css
  Cache-Control: public, max-age=31536000, immutable
/assets/img/*
  Cache-Control: public, max-age=86400
/favicon.svg
  Cache-Control: public, max-age=604800
/apple-touch-icon.png
  Cache-Control: public, max-age=604800
/site.webmanifest
  Cache-Control: public, max-age=604800
${ADS_TAG_ID ? `/assets/js/consent.js
  Cache-Control: public, max-age=3600

# The tag-free CSP, if the tag ever has to come out again:
#  ${CSP_DAY1}
` : `
# The day the Google tag lands, replace the CSP line above by this one (research/13 section 2.3).
# The build does it alone when ADS_TAG_ID is set; this comment is the reference copy:
#  ${CSP_TAG}
`}`);
const ph = Object.entries(COPY).map(([l, c]) => [l, c.reviews.length]).filter(([, n]) => n);
if (ph.length) console.warn('WARNING: ' + ph.map(([l, n]) => n + ' placeholder reviews in /' + l + '/').join(', ') + '. Written by us as placeholders (DECISIONS.md 2026-08-24): before go-live they must carry the real words of real customers, or be emptied so the honest card shows.');
console.log('site-v2 built');
