// English copy for the Pro Débouchage landing page. Mirrors the FR and NL objects in page-template.js.
// Audience: people around Brussels who do not handle an emergency call in French or Dutch (expats,
// international staff, students, embassy and EU people, English-speaking landlords and property managers).
// Same keys and same array shapes as FR, minus langA and langB (the language switcher is owned elsewhere).
// No narrow no-break space: English uses ordinary spacing. Prices in the English convention (€129).
// Flemish Brabant towns in Dutch spelling, Walloon Brabant towns in French spelling.
module.exports = {
  lang: 'en-BE', dir: 'en',
  wa: 'https://wa.me/32480649649?text=Hello%2C%20I%20have%20a%20blocked%20drain.%20Here%20is%20a%20photo%20and%20my%20town%3A%20',
  skip: 'Skip to content', langNav: 'Choose language',
  callHeader: 'Call 0480 649 649', callBar: 'Call 0480 649 649', waBar: 'WhatsApp',
  carAria: 'Photos of our work, swipe to browse',
  chips: ['24/7', 'Price upfront', "30 years' combined experience"],
  h1: `Backing up, overflowing, smelling bad? Call us, we'll take care of it.`,
  sub: `You describe the problem, <span class="hl">we tell you the price on the phone, and that's the price you pay.</span> Confirmed at your door, before the first minute of work.`,
  callMain: 'Call 0480 649 649',
  waBtn: 'Send a photo', under: 'With a photo, we help you faster.',
  collage: [['collage-van.webp', 'hc-van', 'Pro Débouchage van, the logo and the phone number on the side.', 1600, 900],
    ['collage-job1.webp', 'hc-job1', 'Technician in protective clothing in front of the high-pressure machine, at the back of the van.', 800, 1000],
    ['collage-job2.webp', 'hc-job2', 'Technician leaning into an inspection chamber in front of a house, the van is parked in the street.', 770, 962]],
  ticker: [['tick-van.webp', 'The Pro Débouchage van at sunrise, with 0480 649 649 on the side.', 1200, 892],
    ['job-wc.webp', 'Technician unblocking a toilet with a drain snake, in a Pro Débouchage jacket.', 1200, 1500],
    ['camera.webp', 'Inspection camera tablet above an open pipe, the inside of the drain on the screen.', 1200, 1500],
    ['allee.webp', 'Paved driveway being cleaned with high pressure, the light strip is the part that is done.', 1200, 1200],
    ['collage-job1.webp', 'Technician in protective clothing in front of the high-pressure machine, at the back of the van.', 800, 1000],
    ['siphon.webp', 'Inspection of a floor drain with a sewer camera.', 800, 1000],
    ['chambre.webp', 'Opening a buried inspection chamber in a garden.', 800, 1000],
    ['tick-drain.webp', 'Technician clearing a shower floor drain with an electric drain snake.', 800, 1066],
    ['collage-van.webp', 'The van in a garden, the Pro Débouchage logo on the side.', 1600, 900],
    ['collage-job2.webp', 'Technician leaning into an inspection chamber in front of a house, the van is parked in the street.', 770, 962],
    ['moniteur.webp', 'Monitor of the inspection camera and technician in Pro Débouchage clothing.', 800, 1000]],
  carousel: [['car-van.webp', 'The Pro Débouchage van with its rear doors open, ready for the job.', 800, 1000],
    ['machine.webp', 'Rioned high-pressure cleaning machine built into the back of the van.', 1200, 1500],
    ['collage-job2.webp', 'Technician leaning into an inspection chamber in front of a house, the van is parked in the street.', 770, 962],
    ['siphon.webp', 'Inspection of a floor drain with a sewer camera.', 800, 1000],
    ['camera.webp', 'Inspection camera tablet above an open pipe, the inside of the drain on the screen.', 1200, 1500],
    ['tick-drain.webp', 'Technician clearing a shower floor drain with an electric drain snake.', 800, 1066],
    ['moniteur.webp', 'Monitor of the inspection camera and technician in Pro Débouchage clothing.', 800, 1000],
    ['job-wc.webp', 'Technician unblocking a toilet with a drain snake, in a Pro Débouchage jacket.', 1200, 1500],
    ['chambre.webp', 'Opening a buried inspection chamber in a garden.', 800, 1000],
    ['allee.webp', 'Paved driveway being cleaned with high pressure, the light strip is the part that is done.', 1200, 1200]],
  trust: ['You can call in English, day or night', 'Price given on the phone, confirmed at your door', 'Camera inspection included', 'In the Belgian company register (KBO/BCE), BE 1027.454.187'],
  trustShort: ['Call in English, 24/7', 'Price given on the phone', 'Camera inspection included', 'Registered: BE 1027.454.187'],
  priceK: 'The prices', priceH: 'What does it really cost?',
  priceIntro: 'The most common jobs are in this list. For everything else, you get the price on the phone, before we set off.',
  terms: 'VAT included. Call-out and first hour included. On weekdays, from 7am to 6pm.',
  prices: [['Blocked toilet', '€129'], ['Blocked sink, washbasin or shower', '€119'], ['Blocked sewer or outside drain (gully), high pressure', '€199'], ['High-pressure drain cleaning, up to 25 m', '€249'], ['Flooded cellar pumping, first hour', '€229']],
  priceBtn: 'Call', p4t: 'Something else?',
  p4: 'Septic tank, buried pipe, bigger jobs: tell us the problem, you get the price straight away, on the phone.',
  p4b: 'Call 0480 649 649',
  guarH: '1-month guarantee on the unblocking',
  guarP: 'If the same pipe blocks again within 30 days, we come back for free.',
  guarRing: 'GUARANTEE',
  promise: 'The price given on the phone is the price on the invoice.',
  stepK: 'How it works', stepH: 'Four steps, no surprise',
  steps: [['You call and you describe the problem.', 'We ask two or three questions. A photo on WhatsApp helps.'], ['We tell you the price.', 'On the phone, before we set off. Evening and weekend, the surcharge is already in the price you hear.'], ['We come with the camera and the high-pressure jet.', "You get an arrival time, and we'll tell you if it changes."], ['We confirm the price at your door, then we unblock.', "If the situation is different from what you described, you'll hear about it before we start, not on the invoice."]],
  servK: 'What we do', servH: 'Our services',
  services: [['Emergency unblocking', 'Toilet, sink, shower, drain. We come with the high-pressure jet and the camera.', null, null],
    ['Blocked toilets and sinks', '', 'job-wc.webp', 'Technician unblocking a toilet with a drain snake, in a Pro Débouchage jacket.'],
    ['High-pressure cleaning', 'We clean the whole pipe, not just the blockage.', 'machine.webp', 'Rioned high-pressure cleaning machine built into the back of the van.'],
    ['Camera inspection', 'We film the inside of the pipe and you watch the screen with us. Included with the job.', 'camera.webp', 'Screen of the inspection camera showing the inside of a pipe, with the distance counter.', 'Included'],
    ['Septic tank emptying', 'Emptying and check. By appointment.', null, null],
    ['Flooded cellar pumping', 'Pumping, cleaning, and a report for your insurance if you ask for one.', null, null]],
  servLink: 'Call 0480 649 649',
  whoK: 'Who comes to your door', whoH: 'Afrem, the van and the equipment. Not an anonymous number.',
  whoT: 'You call, you speak to the person who organises the job. Afrem is the one who comes, in the van you see here, with the inspection camera, the Rioned high-pressure machine and the pump. A team of two, 30 years in the trade between them: property, renovation and plumbing. The company carries professional liability insurance with AG Insurance.',
  vanAlt: 'Pro Débouchage van, grey Mercedes Vito, with the number 0480 649 649 on the side.', vanCap: 'The van, exactly as it arrives at your door. The number is on it.',
  blocks: [['The camera comes before the hammer.', "We look with the camera first. Breaking is the last resort, and never without your agreement. That's why it's included."], ['A report for the insurance, on request.', 'Ask us, and after the camera inspection we write a report you can give to your insurance company, for example after water damage.'], ['An invoice, every time.', 'Bank transfer, payment link, or cash with a VAT receipt handed to you on the spot. Never an invented amount at the door.']],
  monAlt: 'Monitor of the inspection camera and technician in Pro Débouchage clothing.', monCap: 'The camera screen: you see the inside of your pipe together with us.',
  proofK: 'The proof', proofH: 'What we can show you today',
  honest: "Our Google page is on its way. After every job we ask you for an honest review, good or bad, and we'll publish it here as it is. In the meantime, here's our work.",
  tiles: [['chambre.webp', 'Opening a buried inspection chamber in a garden.', 'Blocked gully, inspection chamber opened. One of our own jobs, 2026.'], ['siphon.webp', 'Inspection of a floor drain with a sewer camera.', 'Camera inspection in a floor drain. One of our own jobs, 2026.'], ['allee.webp', 'Paved driveway being cleaned with high pressure, the light strip is the part that is done.', 'Paved driveway, high-pressure cleaning in progress. The light strip is the part already cleaned.']],
  // PLACEHOLDERS, same three people as FR and NL (DECISIONS.md 2026-08-24): swapped for real
  // customers' words before go-live. The build warns while any are here.
  reviews: [
    ['Paolo', 5, 'I called on a Sunday evening in June, the upstairs toilet was backing up into the shower. Two questions on the phone and I had a price. That same price was on the invoice, not a euro more. He was gone by about midnight and everything worked again. The number is on my fridge now.'],
    ['Daniel', 4, "The drain in our courtyard was overflowing after the May rain. We agreed on Tuesday late afternoon and he turned up half an hour later than that, but he did phone ahead to say so. He put the camera in before touching anything and showed me the roots on the screen. The price was the one I got on the phone."],
    ['Élodie', 5, "Kitchen sink blocked since the weekend, I'd tried everything, the plunger and the shop products. I called on Monday morning, appointment Tuesday at 8am. He took the trap apart, cleaned the pipe and put it all back neatly. The amount quoted on the phone didn't change, and the invoice came the same day."]],
  honestT: "No reviews online yet, and we're not going to invent any.",
  honestP: 'Pro Débouchage is a young company, registered since September 2025. Our first customers came by word of mouth. Our Google page is on its way, and the first reviews will be theirs.',
  honestL: ['Our company number, BE 1027.454.187, which you can check in the public register.',
    'The price, given on the phone before we set off, and confirmed at your door.',
    'The photos above: our own jobs, not bought images.'],
  src: 'Google review', askLine: 'Have you had us out? An honest review helps us more than a compliment.',
  scamK: 'Good to know', scamH: 'How to spot a drain-unblocking scam',
  scamI: 'The Halle-Vilvoorde area is known for it. Four signs that should make you hang up:',
  scam: ['A price that changes once the van is parked.', 'An invoice charged by the metre AND by the hour.', 'No address, no company number, no name.', 'Cash only, with no invoice.'],
  scamC: 'We do the opposite. The price is given on the phone and confirmed at your door, the address and the company number are at the bottom of this page, and you always get an invoice.',
  scamB: 'Call 0480 649 649',
  zoneK: 'The area', zoneH: 'Where we work',
  zoneT: "We're based in Vilvoorde and we work in the ring around Brussels, in Flemish Brabant and Walloon Brabant, about 40 km around Wemmel. Not inside the Brussels Region itself (the 19 communes).",
  towns: `Vilvoorde · Machelen · Wemmel · Meise · Grimbergen · Merchtem · Asse · Dilbeek · Ternat · Zaventem · Zemst · Sint-Pieters-Leeuw · Halle · Beersel · Tervuren · Overijse · Sint-Genesius-Rode · Kraainem · Wezembeek-Oppem · Waterloo · La Hulpe · Braine-l'Alleud · Braine-le-Château · Tubize · Wavre · Nivelles`.split(' · '),
  zoneC: `Don't see your town? Call us and you'll get a yes or a no straight away.`, zoneL: 'Call 0480 649 649',
  faqK: 'Your questions', faqH: 'Frequently asked questions',
  faq: [['How much does it cost?', 'A blocked toilet costs €129, a sink, washbasin or shower €119, a sewer or gully with high pressure €199, high-pressure drain cleaning €249 up to 25 m, pumping a flooded cellar €229 for the first hour. VAT included, call-out and first hour included, on weekdays from 7am to 6pm. For everything else, the price is given to you on the phone before we set off.'],
    ['Is there a surcharge in the evening, at night or at the weekend?', "Yes, and it's written here. Evening (6pm to 10pm) and Saturday: +50%. Night, Sunday and public holidays: +75%. You hear it on the phone, before the job."],
    ['Do I pay for the call-out?', 'No, the call-out and the first hour are included in the prices above. If we come and nothing can be unblocked, you only pay the call-out, €60.'],
    ['Which VAT rate applies to me?', "6% if your home is more than 10 years old, which is the most common case. Otherwise 21%, as for companies. The prices on this page include 6% VAT; if the 21% rate applies to you, you hear it on the phone, before we set off."],
    ['How fast are you there?', "We give you an arrival time on the phone, and we'll tell you if it changes. We'd rather give you a time we can keep than a number that sounds good."],
    ['Will you have to break anything?', "We look with the camera first. Breaking is the last resort, and never without your agreement. That's why the camera is included with the job."],
    ['Do you make a report for the insurance?', 'Yes, if you ask for one. After the camera inspection, we then write a report you can give to your insurance company, for example after water damage or a flooded cellar. The easiest is to say so on the phone.'],
    ['Which towns do you cover?', `The ring around Brussels, in Flemish Brabant and Walloon Brabant: Vilvoorde, Wemmel, Grimbergen, Dilbeek, Halle, Zaventem, Waterloo, Braine-l'Alleud, Wavre, Nivelles and the other towns within about 40 km of Wemmel. Not inside the Brussels Region itself (the 19 communes). Don't see your town? Call and you'll know in seconds.`],
    ['How can I pay?', 'By bank transfer, by payment link, or in cash with a VAT receipt handed to you on the spot. You always get an invoice.']],
  waAria: 'Send a photo on WhatsApp',
  finalH: "A blockage doesn't wait.", finalB: 'Call now', finalWa: 'Send a photo',
  finalL: 'We answer the phone 24 hours a day and 7 days a week, weekends and public holidays included. Normal number, no premium rate.',
  footD: 'Unblocking, drain cleaning, camera inspection, septic tanks and cellar pumping. Around Brussels, in Flemish Brabant and Walloon Brabant, 24/7.',
  legalT: 'Legal information', legal: ['PRO DEBOUCHAGE SRL', 'Guldenschaapstraat 6, 1800 Vilvoorde, Belgium', 'Company number BE 1027.454.187', 'E-mail: info@prodebouchage24.be', 'Phone: 0480 649 649'],
  vat: 'The prices shown include 6% VAT (private homes over 10 years old).', privacy: 'Privacy policy',
  credit: 'PRO DEBOUCHAGE SRL. This site sets no cookies and uses no measurement tools.',
  creditTag: 'PRO DEBOUCHAGE SRL. This site uses one call measurement tool, and only if you accept it.',
  consentT: 'Measuring calls, with your OK',
  consentP: "We use Google's tool to see whether our ads bring in calls. Nothing loads before you choose, and refusing doesn't change your visit.",
  consentRefuse: 'Refuse all', consentAccept: 'Accept all', consentLink: 'Cookies and measurement',
};
